name: Mirror to public (manual)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to mirror
        required: true
        default: main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}

      - name: Push to public
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git fetch --tags --force
          git remote remove public || true
          git remote add public "https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ChrisTsang27/task-management-public.git"
          git push public "refs/heads/${{ inputs.branch }}:refs/heads/${{ inputs.branch }}"
          git push public --tags
