name: Mirror to public (manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: false

      - name: Push to public
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${{ secrets.PUBLIC_REPO_TOKEN }}" ]; then
            echo "ERROR: PUBLIC_REPO_TOKEN secret is missing or empty"
            exit 1
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote remove public 2>/dev/null || true
          url="https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/ChrisTsang27/task-management-public.git"
          git remote add public "$url"

          git ls-remote public >/dev/null

          git push public refs/heads/main:refs/heads/main
          git push public --tags
